### ISSUE TITLE
Footnote space doesn't look good with computeautoilg

### ISSUE THREAD

**Issue by javadr** [tex-xet/xepersian#25]
With the presence of computeautoilg option, space between footnotes doesn't look great. The space between footnotes are so smaller than space between lines of a footnote. The following code depicts the problem. 

```latex
\documentclass{article}

\usepackage{ptext}
\usepackage[computeautoilg=on,]{xepersian}
\settextfont{Yas}

\begin{document}
متن اول\footnote{\ptext*[1]}
متن دوم\footnote{یک پاورقی کوتاهی} 
متن سوم\footnote{\ptext*[2]}
\ptext*[1]

\end{document}
```

![image](https://cloud.githubusercontent.com/assets/1178221/25323384/0bf3409e-28d4-11e7-87a2-78f4ea9ea032.png)

Actually, I mean the space between 3, 2, and a line before don't match with the other lines in the footnote part. 
![image](https://cloud.githubusercontent.com/assets/1178221/25323429/727eb50a-28d4-11e7-9654-690b02ade49f.png)

**Comment by vafa** [comment]
This does not have anything to do with `\baselineskip` since there is no `\par` between consecutive footnotes. If you look at the definition of `\@footnotetext` for instance,  you will see that the parameter `\footnotesep` determines the vertical space between footnotes so you really want to set it manually to `\baselineskip`; e.g.

````tex
\setlength\footnotesep{\baselineskip}
````

**Comment by javadr** [comment]
truly, I meant isn't it better to set that automatically with computeautoilg option?!

**Comment by vafa** [comment]
I am not sure but I re-opened this issues.

**Comment by vafa** [comment]
### Some preliminary analysis

After thinking about this for a while, I realized that this has not got anything to do with the `computeautoilg` option. After all, if you look at the LaTeX source, you will see that the value of `\footnotesep` is different from `\baselineskip`. For instant, if you are using the `article` document class with `12pt` option. the value of `\footnotesep` in the file `size12.clo` is

````tex
\setlength\footnotesep{8.4\p@}
````
where `\p@` is just `pt` unit defined in `latex.ltx` as

````tex
\p@=1pt
````

However, the value of `\baselineskip` is hidden in the definition of `\footnotesize` in the same file

````tex
\newcommand\footnotesize{%
   \@setfontsize\footnotesize\@xpt\@xiipt
...
````
which sets `\baselineskip` to `\@xiipt`.  `\@xiipt` is defined as `12` in the file `latex.ltx`.

### Summary
When you are using the `article` document class with `12pt` option

- The value of `\baselineskip` in footnotes is `12pt`;

- The vertical distance between consecutive footnotes is `8.4pt`

### Conculsion
The user should set the value of `\footnotesep` to the value that pleases him/her and it should not be set by the `computeautoilg` option since the vertical distance between consecutive footnotes is not the same as the value of `\baselineskip` in footnotes.

**Comment by vafa** [comment]
### More analysis
Here are the respective values of `\baselineskip` and `\footnotesep` for different sizes 

First Header | Second Header
------------ | -------------
Content from cell 1 | Content from cell 2
Content in the first column | Content in the second column

**Comment by vafa** [comment]
I have fixed this in [this commit](https://github.com/tex-xet/xepersian/commit/bd009a3ed2d0d4d14bba8db814788af845d1a078). Can you test the output of the following TeX file against latest `xepersian` on GitHub and let me know if there is any issues?

````tex
\documentclass[12pt]{article}
\usepackage{lipsum}
\usepackage{ptext}
\usepackage[computeautoilg=on]{xepersian}
\settextfont{Yas}

\begin{document}
متن اول\footnote{\ptext*[1]}
متن دوم\footnote{یک پاورقی کوتاهی} 
\LTRfootnote{\lipsum*[1]}
متن سوم\footnote{\ptext*[2]}
\ptext*[1]

\noindent
\fbox{\rl{وفا}}\\
\fbox{وفا}
\end{document}
````

**Comment by javadr** [comment]
Appreciate your concern, it looks great.

**Comment by vafa** [comment]
I now accept donations to the xepersian package. Anyone can donate any amount to the xepersian package. If you are interested to donate to the xepersian package, then please email me at `persian-tex@tug.org` and request my bank account details.

The donations allow me to spend more time working on the xepersian package and make it even better. If you know that some other people may also be interested in donating to the xepersian package development, please let them know.
